### ISSUE TITLE
连续标点符号显示错误的问题

### ISSUE THREAD

**Issue by chenjishi** [Amterson/AlginProject#6]
hello，这个项目挺好的，但是我测试了下，标点符号连续的时候没收集全。

这是目前的实现：
![截屏2020-07-24下午2 31 37](https://user-images.githubusercontent.com/1759571/88366093-bdca8a00-cdba-11ea-81da-04e25b944a10.png)
有两处错误：

1，***，...连续符号没有排在一起，前两个符号跟后一个符号隔开了
2，句尾，，，号没排在一起，换行了

其实标点符号连续的情况还不少，改动了一下分词的代码，如下：
从386行开始

![截屏2020-07-24下午2 36 31](https://user-images.githubusercontent.com/1759571/88366270-5103bf80-cdbb-11ea-9565-f77e4e908fcb.png)

优化后的效果如下：

![截屏2020-07-24下午2 39 03](https://user-images.githubusercontent.com/1759571/88366426-b8ba0a80-cdbb-11ea-99f4-5bceb220d2b8.png)

可以考虑下，加入这个功能:)

**Comment by Amterson** [comment]
很高兴收到你的宝贵意见，已按你的修改优化代码！
